stages:
- deploy

deploy:
  image: docker:18
  services:
  - docker:18-dind
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_NAME:latest || true
    - docker build --tag $IMAGE_NAME:$CI_COMMIT_SHA --tag $IMAGE_TAG --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA --tag $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME
    - docker push $IMAGE_TAG
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/python3.9-poetry
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  rules:
  - if: '$CI_COMMIT_BRANCH == "master"'
  - if: '$CI_COMMIT_BRANCH == "development"'
    changes:
    - Dockerfile
    - .lrz.gitlab-ci.yml
