stages:
- deploy

deploy:
  image: docker:28
  needs: []
  rules:
  -   if: '$CI_COMMIT_BRANCH == "main"'
  -   if: '$CI_COMMIT_BRANCH == "development"'
  -   if: '$CI_COMMIT_TAG'
  services:
  - docker:28-dind
  stage: deploy
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker pull $IMAGE_NAME || true
  - docker build 
      --build-arg=COMMIT=$CI_COMMIT_SHA  
      --build-arg=BRANCH=$CI_COMMIT_BRANCH 
      --build-arg=COMMIT_SHORT=$CI_COMMIT_SHORT_SHA
      --build-arg=TAG=$CI_COMMIT_TAG 
      --tag $IMAGE_NAME:$CI_COMMIT_SHA 
      --tag $IMAGE_NAME:latest 
      --tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA 
      --tag $IMAGE_NAME:$CI_COMMIT_REF_NAME 
      .
  - docker push $IMAGE_NAME
  tags:
    - docker
    - privileged
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/python3.9-poetry
