name: "Build and deploy the node + ruby images."

on:
  push: { branches: [main] }
  release:
    types: [published]

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      context: docker-ruby/
      dockerfile: docker-ruby/Dockerfile
      image-authors: "Patrick Stoeckle"
      image-description: "Node+Ruby"
      image-registry: ghcr.io
      image-name: node-ruby
      image-tag: 24.8.0--3.3
      image-title: "Node+Ruby"
    permissions:
      contents: read
      packages: write
